name: Publish documentation

on:
  push:
    branches:
      - main
      - pixi8
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build API docs
        run: npm run docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEVONWARD }}
          external_repository: Makefully-Studios/platypus
          publish_branch: gh-pages
          publish_dir: ./docs/api
          commit_message: Publish API docs
